name: Bit Repairman
markdown: redcarpet
redcarpet:
  extensions:
    - tables
    - no_intra_emphasis
    - underline
    - highlight
pygments: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
